apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: goserver
  newName: rafaelpaes/gitopsvia
  newTag: fccdd86a433349bf0fc9e9136083b6adf3e5a444
