apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: goserver
  newName: rafaelpaes/gitopsvia
  newTag: 48697999c27af28360092daa4cf861dcb43d4740
